### PR TITLE
Bump package version to 2.1.3

### PR DESCRIPTION
**Pull request by nikita-petko**

### CODE REVIEW

**Comment by guidojw** [comment]
Hi @nkpetko,
Been a long time but when I worked on this around a month ago, I found 2 more bugs:

1. https://github.com/guidojw/credits-gibber/blob/91727bebbb69a3dea2415c509303d96467bc08fc/src/commands/credits.ts#L60 if I recall correctly, this has to do with errors thrown by the runTransformFunction not being sent to the errorFunction in the UpdateAsync promise https://github.com/nkpetko/RbxDataStoreService/blob/32120df8d7b8995d92b999e97e16d89b0dedd744/Source/Classes/DataStore.ts#L480, so it hangs forever.
2. https://github.com/guidojw/credits-gibber/blob/91727bebbb69a3dea2415c509303d96467bc08fc/src/commands/credits.ts#L71 UpdateAsync returns the old instead of new data, I think result here should be r https://github.com/nkpetko/RbxDataStoreService/blob/32120df8d7b8995d92b999e97e16d89b0dedd744/Source/Classes/DataStore.ts#L166

**Comment by nikita-petko** [comment]
For number 1, I'll just put it into a .then() .catch() statement, and for the second one it should be as simple as changing it from `result` to `res` (which is the deserialised value)

**Comment by nikita-petko** [comment]
@guidojw extension on what I mean for the runTransformFunc part:

```ts
this.runTransformFunction(key, transformFunction)
    .then(resumeFunction)
    .catch(errorFunction);
```

**Comment by guidojw** [comment]
> 
> 
> @guidojw extension on what I mean for the runTransformFunc part:
> 
> ```ts
> this.runTransformFunction(key, transformFunction)
>     .then(resumeFunction)
>     .catch(errorFunction);
> ```

Sounds good, I guess the callbacks in those promises don't need to be async anymore then

**Comment by nikita-petko** [comment]
@guidojw I will fix it properly later, at work right now

**Comment by nikita-petko** [comment]
@guidojw could you also try taking a crack at a fix yourself? I'm just backed up with work and I could do with a PR

**Comment by guidojw** [comment]
Will do in a few hours 👍🏿

**Pull request closed without merging**
